config/routes.rb
Rails.application.routes.draw do

  get 'visualizations/index'

  get 'viz/index'

  post 'viz/store_markup'

  post 'viz/del_markup'

  get 'viz/allCorpus'

  get 'viz/markupView'

  get 'viz/manualCatTool'

  get 'viz/timelineWithBrush'

  get 'viz/retrieve_session'

  get 'markup/' => 'markup#index'

  post 'markup/store_markup' => 'markup#store_markup'

  post 'markup/del_markup' => 'markup#del_markup'

  post 'markup/update_markup' => 'markup#update_markup'

  get 'markup/manualCatTool' => 'markup#manualCatTool'

  get 'markup/display_kata' => 'markup#display_kata'

  get 'markup/timelineWithBrush' => 'markup#timelineWithBrush'

  get 'markup/retrieve_session' => 'markup#retrieve_session'

  get 'markup/markup_comparison' => 'markup#markup_comparison'

  get 'markup/:researcher' => 'markup#researcher'

  get 'completed/' => 'completed#index'

  post 'completed/update_completion' => 'completed#update_completion'

  get 'completed/timelineWithBrush' => 'markup#timelineWithBrush'

  get 'completed/mark_kata/' => 'completed#mark_kata'

  get 'completed/:kata' => 'completed#mark_completed'

  get 'cycle_catagorizer/cycle_catgories'

  get 'cycle_catagorizer/parseCSV'

  get 'cycle_catagorizer/listCC'

  get 'cycle_catagorizer/ListKatasInDojo'

  get 'cycle_catagorizer/ImportAllKatas'

  get 'cycle_catagorizer/buildCycleData'

  get 'cycle_catagorizer/ListAllCompiles'

  get 'cycle_catagorizer/InsertTestCompiles'

  get 'grader/index'

end

app/models/cycle.rb
class Cycle < ActiveRecord::Base
  belongs_to :session
  has_many :phases
  #has_many :compiles, :through => :phases
end

app/controllers/cycles_controller.rb
class CyclesController < ApplicationController
  before_action :set_cycle, only: [:show, :edit, :update, :destroy]

  # GET /cycles
  # GET /cycles.json
  def index
    @cycles = Cycle.all
  end

  # GET /cycles/1
  # GET /cycles/1.json
  def show
  end

  # GET /cycles/new
  def new
    @cycle = Cycle.new
  end

  # GET /cycles/1/edit
  def edit
  end

  # POST /cycles
  # POST /cycles.json
  def create
    @cycle = Cycle.new(cycle_params)

    respond_to do |format|
      if @cycle.save
        format.html { redirect_to @cycle, notice: 'Cycle was successfully created.' }
        format.json { render :show, status: :created, location: @cycle }
      else
        format.html { render :new }
        format.json { render json: @cycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cycles/1
  # PATCH/PUT /cycles/1.json
  def update
    respond_to do |format|
      if @cycle.update(cycle_params)
        format.html { redirect_to @cycle, notice: 'Cycle was successfully updated.' }
        format.json { render :show, status: :ok, location: @cycle }
      else
        format.html { render :edit }
        format.json { render json: @cycle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cycles/1
  # DELETE /cycles/1.json
  def destroy
    @cycle.destroy
    respond_to do |format|
      format.html { redirect_to cycles_url, notice: 'Cycle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cycle
      @cycle = Cycle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cycle_params
      params[:cycle]
    end
end

app/helpers/cycles_helper.rb
module CyclesHelper
end

app/views/cycles/_form.html.erb
<%= form_for(@cycle) do |f| %>
  <% if @cycle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cycle.errors.count, "error") %> prohibited this cycle from being saved:</h2>

      <ul>
      <% @cycle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cycles/edit.html.erb
<h1>Editing cycle</h1>

<%= render 'form' %>

<%= link_to 'Show', @cycle %> |
<%= link_to 'Back', cycles_path %>

app/views/cycles/index.html.erb
<h1>Listing cycles</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cycles.each do |cycle| %>
      <tr>
        <td><%= link_to 'Show', cycle %></td>
        <td><%= link_to 'Edit', edit_cycle_path(cycle) %></td>
        <td><%= link_to 'Destroy', cycle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cycle', new_cycle_path %>

app/views/cycles/new.html.erb
<h1>New cycle</h1>

<%= render 'form' %>

<%= link_to 'Back', cycles_path %>

app/views/cycles/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_cycle_path(@cycle) %> |
<%= link_to 'Back', cycles_path %>